---

- hosts: aws
  connection: ssh
  remote_user: ec2-user
  become: yes
  gather_facts: yes

  tasks:
  - name: Execute All Installations
    yum: name={{ item }} state=latest

    with_items:
      - httpd
      - wget
      - openssl

    notify:
      - CopySiteFiles
      - RestartHTTPD
      - WaitForSite
      - TestSite
      - DisplayOutput


  - name: RestartHTTPD
    service: name=httpd state=restarted

  - name: CopySiteFiles
    template:
      src: ../templates/index.html.j2
      dest: /var/www/html/index.html
      owner: root
      group: root
      setype: httpd_config_t
      mode: '0655'

    
  - name: WaitForSite
    wait_for: host={{ ansible_nodename }} port=80 delay=5

  - name: TestSite
    uri: url=http://localhost
    register: site_result

  - name: DisplayOutput
    debug: var=site_result
