--- 
- hosts: local
  connection: local
  remote_user: ec2-user
  become: yes
  gather_facts: no
  vars_files:
  - ../files/awscreds.yml
  tasks:
  - name: Basic provisioning of a t2.micro EC2 instances
    ec2: 
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      image: ami-3883a55d
      instance_type: t2.micro
      count: 1
      assign_public_ip: yes
      vpc_subnet_id: subnet-1299e77b
